### ISSUE TITLE
Keep track of offices that are "open" or "closed" in the BallotStore

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1243]
### Please describe the issue (What happens? What do you expect?)
Our new ballot interface allows the voter to open (or "unfurl") an office to see all of the candidates under that office. You can then click away from the ballot, and click back. We want to store which offices are "open" (in the BallotStore) so that when we return to the ballot the state of the ballot is preserved. Currently everything rolls back up when you return.

**Comment by chulinguy** [comment]
Can I take this issue?

**Comment by DaleMcGrew** [comment]
Hi Chi Jen, yes please feel free to take this issue.

**Comment by chulinguy** [comment]
I am a bit stuck (mostly due to unfamiliarity with Flux?) ... 

I created a new method in BallotAction that executes Dispatcher.dispatch(<path>, <data>) so this method is called when the ballot items will unmount ... the dispatch code executes OK but BallotStore.reduce() is not observing this action ... any tips?

**Comment by chulinguy** [comment]
Got this working on my local version, did a Git pull and noticed some changes on the Master branch:  some variables names were changed and also there is a new functionality to keep the offices open if there are 3 or fewer, so I'll need to worked out the merge conflict tomorrow

**Comment by DaleMcGrew** [comment]
Done!

**Comment by DaleMcGrew** [comment]
Verified! Thank you @chulinguy.
