### ISSUE TITLE
Signing out should clear data out of FriendStore

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1262]
### Please describe the issue (What happens? What do you expect?)
If you have friends attached to your account and then you sign out, the data in FriendStore is not cleared out, so it looks like you have friends when you aren't signed in.

All of the stores to clear out upon sign out:
- [ ] BallotStore
- [ ] BookmarkStore
- [ ] DonateStore
- [ ] FacebookStore
- [ ] FriendStore
- [ ] IssueStore
- [ ] OrganizationStore
- [ ] SupportStore
- [ ] TwitterStore
- [ ] VoterSessionStore
- [ ] VoterStore

**Comment by chulinguy** [comment]
I forgot to ask about this ... are there other stores that you'd like to clear on signing out?  
My best guess would be to also clear VoteGuideStore, VoterSessionStore, VoterStore, TwitterStore, and FacebookStore.  It seems to be a good idea to keep the other stores to make the app load faster for the next user?

**Comment by DaleMcGrew** [comment]
Thank you @chulinguy, I just updated this issue with all of the stores to clear out.

**Comment by chulinguy** [comment]
@DaleMcGrew thanks! Follow-up question:

1) it seems to be that when the voter does a Facebook or Twitter sign out, the app will then load voterRetrieve() so the voter is technically still signed in on WeVote with email instead of Facebook/Twitter?
Is that the right behavior or should any signing out completely signs out the user?  

2) the VoterSessionStore does not seem to be storing any meaningful data? What is the intent to try to sign out with VoterSessionAction if VoterSessionStore is not necessary?

**Comment by DaleMcGrew** [comment]
Hi @chulinguy, 
1. When we get a response from "voterSignOut" it triggers action in VoterStore, and FacebookStore. The action in VoterStore just sets up a new user, which I'm realizing I need to look at. Maybe the answer is to create an entry in every store that responds to "voterSignOut" by clearing the store variables, like we do partially do in FacebookStore.
2. You are correct VoterSessionStore isn't storing data, so I have removed that from the list.
