### ISSUE TITLE
Can no longer start the Webapp server due to missing jQuery

### ISSUE THREAD

**Issue by chulinguy** [wevote/WebApp#1288]
### Please describe the issue (What happens? What do you expect?)
I updated my fork from wevote/WebApp master and could no longer start the server.  I deleted my fork and did a fresh clone of wevote/WebApp master and this issue still persists! 
![jquery error](https://user-images.githubusercontent.com/25993366/35363560-6a6d1b76-011f-11e8-8cd5-69091ad8342b.JPG)

### Steps to reproduce the problem (1, 2, 3...), including links
1. Fresh clone of wevote/WebApp
2. yarn start

**Comment by DaleMcGrew** [comment]
Thank you for reporting this @chulinguy, I have asked @edward-ly if it is because of a recent addition he made.

**Comment by edward-ly** [comment]
`Error: Cannot find module 'jquery' from 'C:\Users\Meechrox\WebApp\src\js\components\Widgets'`

For some reason, it's looking for jQuery in the same folder where `ItemSupportOpposeRaccoon.jsx` is rather than in `node_modules` where the package should be. Do you have Node.js installed on your computer?

**Comment by chulinguy** [comment]
I don't think "yarn start" would even run if I don't have Node.js installed ... 

The webApp server started correctly for me for several weeks until today when I updated my fork.

**Comment by edward-ly** [comment]
Is `jquery` in your `node_modules` folder, then? If not, try installing it and/or adding it to `package.json`.
