### ISSUE TITLE
address validation

### ISSUE THREAD

**Issue by lisamcho** [wevote/WebApp#139]
Click on address and enter bogus text (i.e. asdf) and hit Save.
The backend saves the bogus address to text_for_map_search and now all attempts to fetch the ballot result in server errors.

VoterAddressSave should not save the address if it is not valid, return appropriate error message? Then address component can handle gracefully with message to user.

**Comment by nf071590** [comment]
How do you know that the user has typed in a bogus address? I’m not sure if there is a regex for that. Wouldn’t you have to search a DB for address?

**Comment by lisamcho** [comment]
@nf071590 Agree, no regex for that. I suppose the frontend could validate for empty string, but all other invalid addresses probably need to be detected by backend.

**Comment by DaleMcGrew** [comment]
The  API server accepts empty strings in case a voter wants to blank out their address for some reason.

**Comment by lisamcho** [comment]
@Dale why would user want to blank out their address? Is this where the frontend is supposed to redirect to the Address page if you click on Ballot? Also API returns 500 error when you try to save "asdf" so that is definitely a change needed on backend right?

**Comment by DaleMcGrew** [comment]
As we add more features, a voter might want to use those other features without saving an address. They might feel uncomfortable sharing their address for some reason and want to erase it.

You are correct, if you click ballot and there is no address, it should redirect to the "My Ballot Location" page. I think it is ok to return success = true with a garbage address, because I added a variable "ballot_found" which returns "false" when a ballot doesn't exist for an address. We can discuss. It will just be very difficult to tell if we have a good address and no ballot or a bad address and no ballot.

**Comment by lisamcho** [comment]
So the 500 API Error was from the invalid voter, not related to this.
But to be clear.. You want user to be able to save their address as "asdf"? I think pretty much all websites I've used prevent you from saving junk as your address with an error message and leave your address as it was until you enter something valid. WeVote API currently saves "asdf" to the database which I find very weird.

**Comment by DaleMcGrew** [comment]
Yes, for now we want the voter to be in total control of that address text. We can react to useless address text by giving feedback to the user. I know it is a different philosophy than most websites, but it is intentional. I am not able to reproduce an error saving asdf -- can you describe steps?

**Comment by DaleMcGrew** [comment]
Will not fix. One we we may ensure better addresses is by using instant search for the address (via Google) as people are entering an address.
