### ISSUE TITLE
Following/Unfollowing orgs should update positive/negative counts without browser refresh

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#141]
1. Find a ballot
2. Go to the More Opinions page and Follow orgs
3. The positive/negative counts don't update until you do a browser refresh.

Discuss a strategy for updating the positive/negative counts on the ballot without requiring a browser refresh.

**Comment by lisamcho** [comment]
Ballot is currently being reloaded everytime the page mounts to get around this issue (thought we would make it more efficient in later versions), so browser refresh shouldn't affect it. 

Are you positive the support/oppose counts are being updated after the refresh? I can't get the negative/positive counts to go beyond +1 and -1 (which is my own support/oppose opinion), no matter how many times I refresh or how many organizations I follow.

The organization follow is definitely being recorded (since refreshing the 'opinions I'm following' page shows the same organizations).

**Comment by DaleMcGrew** [comment]
Hi Lisa, with my latest pull request, which removes the "use_test_election" when voterBallotItemsRetrieve is called, you can use this address "Columbus, OH 43202" and then follow the top 20 or so orgs. When you refresh your ballot you will see Bernie Sanders has 12 positive and 6 negative. If you then stop following 5+ orgs on the "Opinions I'm Following" page and then return to the ballot, the numbers "12 positive and 6 negative" remain unchanged.

PS. There were problems with the voterGuidesToFollow and voterGuidesFollowed API endpoints that I fixed about an hour ago.

**Comment by lisamcho** [comment]
We could do this by simply reloading those numbers everytime the page mounts. With infinite scroll in place in the future it wouldn't be quite as bad performance wise. Alternately, what about creating a voterSupportCountsRetrieve endpoint that returns a list of we_vote_ids and their respective counts of support and oppose for opinions voter follows? Could replace the 2xN queries on page load as well....

**Comment by DaleMcGrew** [comment]
Hi @lisamcho, I think having an API endpoint that packages up all of the support/oppose values makes sense. Maybe it could get called when the voter views the ballot page (as opposed to every time there is a change in Follow status) to prevent churning. I could also do one for star status.

**Comment by lisamcho** [comment]
Now that support/opposes are a single api call, I just said to fetch them everytime you mount the ballot. That should fix this. #184

**Comment by DaleMcGrew** [comment]
Verified.
