### ISSUE TITLE
HeaderBackToBar.jsx Alignment Styling

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1463]
### Please describe the issue (What happens? What do you expect?)
Left and right align these buttons (as opposed to them floating into the center):
![screen shot 2018-04-23 at 9 13 19 am](https://user-images.githubusercontent.com/7756031/39139892-f2bbda00-46d7-11e8-9650-da8ad208a6e6.png)

...on this page: WebApp/src/js/components/Navigation/HeaderBackToBar.jsx

**Comment by ndrewr** [comment]
Issue is caused by an old "clearfix hack" that I guess was common to use with bootstrap grids.

The `.page-header` class uses the clearfix mixin which doesn't sit well with flexbox simultaneously acting on the element. Two components use the above class. I commented out the mixin and tested the app for a bit and there seems to be no noticeable ill effects (in desktop and mobile views).

There was another styling issue as well; when the profile button is clicked a "popup" with menu options becomes visible but it affects the layout of the items in the header:

![screen shot 2018-04-26 at 2 41 21 pm](https://user-images.githubusercontent.com/9262383/39333509-fae8b8d0-495f-11e8-8913-cb639d86c5b7.png)

this is independent of the issue above and happens with or w/o the "clearfix" hack applied.

**Comment by DaleMcGrew** [comment]
Ahhhhh, this looks so much better now @ndrewr -- thank you for fixing this!
