### ISSUE TITLE
Add horizontal line separating two candidates.

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1479]
### Please describe the issue (What happens? What do you expect?)
We would like to add a faint gray horizontal line between candidates. It should start near the margin on the left side and end before the margin on the right side. We are emulating how Apple provides visual separators in lists, so please try to find an example in an Apple product if possible.

<img width="630" alt="screen shot 2018-04-25 at 5 16 08 pm" src="https://user-images.githubusercontent.com/7756031/39279243-a05d99de-48ac-11e8-9d70-466840b080da.png">

Here is one example:
<img width="297" alt="screen shot 2018-04-25 at 5 20 49 pm" src="https://user-images.githubusercontent.com/7756031/39279307-1113c478-48ad-11e8-996d-f146fe7fe92e.png">

**Comment by juanhurtado4** [comment]
Hey Dale how are you?

I was wondering if I could be assigned this issue?

**Comment by DaleMcGrew** [comment]
Hello @juanhurtado4 -- it is yours! I just sent you an invite to the We Vote team, and once you approve I can add you to the "Assignees" field.

**Comment by juanhurtado4** [comment]
Awesome I just approved the invite. Thanks!

**Comment by juanhurtado4** [comment]
<img width="611" alt="screen shot 2018-04-28 at 8 18 42 pm" src="https://user-images.githubusercontent.com/30597759/39402894-70bf5290-4b21-11e8-9787-3fb25c319394.png">

Hey @DaleMcGrew, I believe I was able to get the styling down per the example that you gave. However, I am having a bit of a problem contributing due to the following:

- I am not sure where to make my changes. I read the *styleguide* but I am not sure if `_u-layout.scss` is the correct file to edit.

- When I attempt `npm start` I get this error: `Failed at the wevoteusa@1.0.0 start script.` I uninstalled and reinstalled the node_modules and it didn't work.

Sorry if these are trivial questions, I don't want to be a nuisance. First time contributing to your project and I want to do things the right way.

Thank you.

**Comment by DaleMcGrew** [comment]
That looks great @juanhurtado4! I think there is a sass/components/ballotlist.scss file (or something like that) you can use. I’m happy to help you debug the issue with npm start, and I’ll reach out when I’m next at my computer.

**Comment by DaleMcGrew** [comment]
Hello @juanhurtado4, we could work together to resolve this at Code for SF this Wednesday, or Thursday at 5pm. Please let me know which time works for you. Thank you.

**Comment by juanhurtado4** [comment]
Hey Dale,

Yea that sounds good. Definitely want to get that resolved, I’ve been very busy with work and personal things but I am looking forward to it. Also, I got Webstorm because of your suggestion and it is an awesome IDE. By far the best I’ve used so far.

Juan Hurtado
Email: juanhurtado4@outlook.com<mailto:juanhurtado4@outlook.com>





On May 29, 2018, at 9:43 AM, Dale John McGrew <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @juanhurtado4<https://github.com/juanhurtado4>, we could work together to resolve this at Code for SF this Wednesday, or Thursday at 5pm. Please let me know which time works for you. Thank you.

**Comment by DaleMcGrew** [comment]
Thank you @topdreg for resolving this!
