### ISSUE TITLE
Create a living style guide that displays multiple components on a single page

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#154]
Build out a team-only JSX page that includes various components. This will allow us to A) add comments (hardcoded into the page) that discusses the design elements, B) give developers code examples showing how to style new pages, C) confirm visually in one place that CSS changes haven't "broken" a desired look.

Full description (with video) here:
http://engineering.lonelyplanet.com/2014/05/18/a-maintainable-styleguide.html
Thanks to @ixley for this idea.

**Comment by pertrai1** [comment]
Here are some very good examples for reference: http://styleguides.io/examples.html

**Comment by ixley** [comment]
@pertrai1 I've looked at a number of those – it's definitely a great resource. The reason I specifically suggested referencing Lonely Planet's implementation, is because it's one of the only efforts (I'm aware of) that has successfully (and publicly) created a truly living style guide. 

By building almost everything with component APIs, they are able to use a single design system for production templates as well as their style guide, in a highly modular way with almost no redundancy. This is the real appeal since most other attempts to maintain style guides eventually fall apart for not being integrated tightly enough with the actual product.

**Comment by pertrai1** [comment]
@ixley That is great that you want to contribute and if putting together the starting of the living style guide, that would be awesome. If you are, we can assign this to you and get you up and running.

**Comment by ixley** [comment]
I don't think I quite have the right combination of experience + time to be
the one that spearheads this, but perhaps I could work with a developer to
begin outlining it?

**Comment by DaleMcGrew** [comment]
After conversation in mini-hackathon, @pertrai1 will implement an auto-style-guide-creator in conversation with @ixley.

**Comment by ixley** [comment]
Goals:
- document the styles, patterns, and conventions using agreed shared vocabulary
- ensure a consistent use of patterns and UI elements (and guidance on usage of patterns)
- encourage re-use of code, keeping redundancy to a minimum

Assumptions:
- It's a place where someone can easily see and review the wider-reaching implications of style changes
- The guide renders code snippets and styles from the same source that the app does (doesn't rely on divergent codebases) so that edits only get made in a single location (or are automatically bidirectional?)
- Contributors can get a helpful overview of the app's core styles, components, and approach

Does this sound right? Anything to edit or add? @pertrai1 @DaleMcGrew

**Comment by ixley** [comment]
@pertrai1 I took a look at the SC5 Styleguide engine, and while I didn't completely wrap my head around everything it does, it looks pretty good on the surface. Did you have any other tools you think are worth reviewing alongside this one? 

In particular, I wasn't clear what sort of tradeoffs might be involved with allowing style edits directly from the guide, and how much additional complexity this would potentially introduce. Can you speak to that? My original imagining of this did not involve any actual editing abilities from within a guide/library, but I could see how it might be useful. I can also imagine how it would be one more layer of (unnecessary) abstraction to support, so I'm interested to hear about your experience with it and what sort of value you think the direct editing capability brings. Would you still recommend this tool even if the editing capabilities weren't an expectation?

**Comment by pertrai1** [comment]
@ixley We had no use of the ability to edit from the style guide. We used it strictly for the ability to iterate quickly with the designers as they could see what the values were for colors, type, box layout, etc. What it is really good for is that it makes you put the rules in files that are relevant, and it is from within those files that you add the comments that are used to build out the style guide. Most of the style guides that use KSS are good to look at, and so far this one in particular had the most value. During the time using it I did not look into whether editing straight from the style guide can be turned off or not. I never even looked into it or bothered with it once it was set up for the designers. Maybe play around with it and see if it actually saves the edits or just allows you to see what the changes would look like with the edits.

**Comment by ixley** [comment]
@pertrai1 aha - so perhaps I just misunderstood editing ability piece. And now I see that the snippets it renders come from comments within the stylesheets (I'm guessing this is part of the KSS notation). 

What I am still hoping for is a guide that is able to display more complex patterns (rather than just basic elements), that also doesn't require redundant code (writing example snippets separately).

If you look at either [Lonely Planet's guide](http://rizzo.lonelyplanet.com/styleguide/ui-components/) or [Future Learn's pattern library](https://www.futurelearn.com/pattern-library) – they are rendering (at least slightly more complex) modules. 

**I don't want to put the cart before the horse**, but my impression was that it would be helpful to be able to see full components (such as the Candidate Card) within the guide and that to do that, you'd want to make sure it was rendering exactly what was being used in the app.

Thoughts?

**Comment by pertrai1** [comment]
@ixley - After looking at the concept in more detail - https://github.com/lonelyplanet/rizzo - at this time in the life cycle of our application, I don't feel we are at a place for a style guide UI implementation. A couple of blockers would be that we don't have a style yet, and we would have to take their code base - which is Ruby - and change it to React so that it can live inside of our React components. My preference would be to backlog this until we start to put a style on top of the components we create and start to implement the style guide procedures used in the repo listed above. 

CC: @DaleMcGrew

**Comment by ixley** [comment]
That sounds totally reasonable. I mentioned this to Dale initially because I thought this approach would fit well with this project, but I didn’t expect it to be a priority and I had no sense of what the technical cost would be. 

It might still make sense to put together a lighter weight style guide as we develop a style, for documentation and reference as we go. This doesn’t necessarily need to have an engine or framework behind it though—I just want it to be code based. I'll think on this as we begin to establish more of a visual style. 

I appreciate the input and dialogue @pertrai1!

**Comment by pertrai1** [comment]
@ixley Was playing around and one of the newsletters showed this off: http://atomicdocs.io/

**Comment by ixley** [comment]
@pertrai1 Sweet - thanks for sharing. So many good options! Once I get a chance, I will probably try to pick something lightweight (per our previous discussion) that references the majority of our components and styles without too much redundancy or set up.

**Comment by DaleMcGrew** [comment]
I am closing this for now until someone wants to actively pick it up and work on it.

**Comment by ixley** [comment]
Reviewing https://github.com/styleguidist/react-styleguidist as an option...

**Comment by ixley** [comment]
@pertrai1 Any chance you might have time to evaluate and/or help with basic set up for React Styleguidist? Your expertise would be greatly appreciated on this.

In case you didn't see my request on Slack, I attempted setting this up myself but ran into problems that were over my head. The tool looks like a good candidate for supporting a living and integrated style guide (+ component library) but it'd be really helpful to get your opinions since you can better evaluate the technical side of this and also have a good understanding of its relevance.

**Comment by pertrai1** [comment]
@ixley yeah I just took a look at this and can certainly help getting this setup and start with some of the components. Once that happens you can get a good idea of how to add the documentation that will build out the style guide.

**Comment by ixley** [comment]
@pertrai1 That'd be awesome, thanks! 

My impression/hope is that it:
1. would allow us to visualize and document styles AND components in an orderly way without the need for redundant code
2. would integrate well with We Vote's setup and processes
3. is well-built and likely to be well-maintained moving forward
4. would ideally help contributors reference existing styles and patterns and support good practices as we continue to build things out

My ultimate desire is that a tool like this would help support miscellaneous contributors in contributing to a more cohesive system (to educate and help maintain standards) and encourage development of more high-quality (reusable) components and patterns. I don't mean to put all those aspirations on a single tool, but I'd like a tool that feels like it's worth investing in and doesn't require much customization in itself. 

Does that sound _mostly_ reasonable?

**Comment by pertrai1** [comment]
@ixley @DaleMcGrew  Looking over the documentation, there is no problem with the living style guide being built right from the source code of each component. What could be the problem is that there is a code style that anyone who works on the app will abide by. If there is not, then the style guide will not be worth documentation. If you believe that there can be a way to enforce commenting the props, states, etc. in the files, I am all for getting this setup. Should not take me long at all getting the ball rolling and having it ready to be populated. 

@ixley everything you asked for in the previous comment can be done

If this moves forward, reopen this and I will create branch against this issue.

Rob

**Comment by ixley** [comment]
Thanks, @pertrai1. That's a good point about code style and hopefully something you can weigh in on a bit more. I have a desire to see the code quality continue to improve and my hope was that a tool like this would at least passively aid in that effort—but I do also understand there needs to be some degree of active oversight and effort to follow certain conventions, something I am less qualified to do in this context.

I have a joint interest in seeing components develop and get used in a more modular and consistent way AND making it easier to assign specific styles and variables to them—both in support of making it easier for people to build with pieces that are harder to break or misuse. It's certainly NOT something I can do on my own though, which is partly why I haven't pushed harder for this in the past year.

@DaleMcGrew Do you want to weigh in since you would also be assuming some involvement with helping contributors adhere to certain guidelines and standards? Does We Vote feel like it's at a place where this could be reasonably supported (and the value justifies the setup and maintenance cost)? _This probably depends on having at least one or two contributors that are strong with React and also invested in this approach._ 

A few more questions...
- Just to confirm - Does it seem like this approach would work fine with our existing reliance on compiled Sass files and allow for an eventual/gradual shift towards styling in JS down the road?
- Would we be able to document components pulled in from other projects (react-bootstrap, for example), or would this only support custom components we create?
- How unique or burdensome do you think the required code formatting for this would be?
  - and... will this help enforce/encourage more universal good practices for structuring components or is much of the required structuring just specific to what react-styleguidist needs?

**Comment by DaleMcGrew** [comment]
I think We Vote will benefit greatly from a living style guide, and I will work to maintain consistent styles. Thank you @pertrai and @ixley

**Comment by pertrai1** [comment]
I will be starting this tonight on a new branch and see what happens when I do.

**Comment by pertrai1** [comment]
@ixley @DaleMcGrew - Unfortunately this does not look like it is going to work at this time with the code base. There are dependencies that are needed such as `prop-types` which is only supported in v15 and higher for React. `PropTypes` has been deprecated and it throws errors when trying to build the `AST` from the code. I also noticed there are a great deal of code style issues that my JSCS picked up when looking at the files that were causing issues with the likes of `PropTypes` being used. Unless there is a major change to the semantic version of the app, I do not see this being a valid solution.

**Comment by ixley** [comment]
@pertrai1 ah.. that's too bad. Thanks for giving it a shot. I don't have a sense of how much work is involved, but maybe once we upgrade to React v15 we can revisit this...

**Comment by DaleMcGrew** [comment]
Thank you @pertrai1 and @ixley for pushing for this. Here is the React v15.0 announcement: https://facebook.github.io/react/blog/2016/04/07/react-v15.html
We will want to upgrade to React v15, but we are very close to our MVP and I’d like to upgrade after we have a complete working version, probably after we run the November 2017 elections.

**Comment by DaleMcGrew** [comment]
I am closing this for now -- we can reopen after we upgrade to React v15.
