### ISSUE TITLE
"What I've Bookmarked" page

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#171]
- [ ] Add version of /src/js/routes/Ballot/Ballot.jsx page that only shows offices + candidate and measures that a voter has starred
The new API endpoint is available: https://api.wevoteusa.org/apis/v1/docs/voterAllStarsStatusRetrieve/

**Comment by lisamcho** [comment]
So if we use the Ballot view, candidates are nested under offices and both are star-able. If the voter has NOT starred an office, but HAS starred a candidate for that office, then do you show the unstarred office anyway?

**Comment by DaleMcGrew** [comment]
That's correct! Thank you.

**Comment by lisamcho** [comment]
That is kind of odd logic. I don't get the point of "starring" candidates. Why not just allow starring on offices and measures and not candidates? If you are interested in a candidate you can support/oppose them.

Otherwise I think that 2 of the 4 possibilities don't make a lot of sense.
A) User has starred an office, not starred any candidates under it => show just the office.
**(Maybe they starred the office because they're interested in following the election/ choosing a candidate later, in which case not showing unstarred candidates is weird).**
B) User has starred an office and starred some candidates as well => show office + starred candidates
**Makes sense**
C) User has not starred an office, or any candidates under it => show nothing
**Makes sense.**
D) User hasn't starred an office, but has starred candidates under it => show office + the starred candidates.
**(Odd because now we have unstarred items on the starred items page).**

**Comment by DaleMcGrew** [comment]
Hi @lisamcho thank you for articulating the logic/scenarios. Starring is just like how stars are used in Gmail. It is a reminder to spend more time on something (i.e., come back to it later). A voter might think: 
"Heck, I don't know which District Attorney to support. I'm going to star the office and think about it later."
"Bernie or Hillary? How will I ever decide? I'm going to star both and come back to this decision."
Also, stars are private, and Support/Oppose will be visible to the Voter's friends, so a voter might not want to express support for both Bernie and Hillary.

Cases A & B)
I think that starring an office would most likely mean that they need to come back to the office and review all candidates. In the future (not needed for version 1) we could "roll-up" candidates (under a starred office) that aren't starred (and offer a small photo/candidate name in tiny text that you could click to unfurl), so a voter could have a way on the "What I've Starred" to see the candidates under an office, even if they haven't starred the candidates. Candidates that are starred, under an office that is starred, would be more prominent.

Case C)
Correct, no stars for office/candidates means they are completely gone from list.

Case D)
option D1) (preferred)
Show them under the (unstarred) office name. This would be different than Cases A & B because if a candidate is starred and the office isn't, I don't think we need to show "rolled up" links to the other candidates under that office. If the voter then stars the office, "rolled up" links to all of the other candidates would appear.
option D2)
Starring Bernie & Hillary would only show the ballot list candidate card for both of them. We might want to add "Running for President" somewhere on the candidate card, since the person will now be out of context.

**Comment by pertrai1** [comment]
@DaleMcGrew This issue and those from 1.0 should be moved to another milestone so this milestone and 1.0 can be closed and 1.0 can be tagged.

**Comment by pertrai1** [comment]
@DaleMcGrew I am still wondering why this is stuck in this milestone. We have passed the milestone and this was not completed. My idea of milestones is that you set it and reach it. Anything that is committed to during that milestone will be completed, otherwise it is moved out. Also, we are not using semver, which leads me to trying to understand the semantics of the versioning of the application? I hold to my previous note that this should be pulled out into another current milestone so we can tag and move forward with the next release.

**Comment by DaleMcGrew** [comment]
This is great @lisamcho! Verified.
