### ISSUE TITLE
"You Support" item - Should not link to organization page

### ISSUE THREAD

**Issue by lisamcho** [wevote/WebApp#217]
If you support a candidate it shows up in the opinions under each candidate on the candidate page with the text "You Support" and a link to an organization page with a "null" we_vote_id.
It's pretty weird. Should we be showing these as opinions? Seems weird.

**Comment by DaleMcGrew** [comment]
You are right @lisamcho this needs to be fixed. Thank you for reporting.

**Comment by lisamcho** [comment]
@DaleMcGrew I was thinking that the backend should not return these items. Whether you support/oppose an organization is shown by the Support/Oppose arrows. Why show it twice? Also, if you click the arrows to change your mind, we'd have to make the "you support" item disappear in order for the page to stay accurate which would be a weird jump in the UX.

**Comment by DaleMcGrew** [comment]
@lisamcho it is there for when you add a comment in addition to support or oppose. Shall we discuss the various cases tomorrow?

**Comment by lisamcho** [comment]
per discussion lastnight, we shouldn't show this. @dale are you planning to remove this item on endpoint response then? (close this issue and open one on wevoteserver)?

**Comment by DaleMcGrew** [comment]
Hi @lisamcho you are correct we should not be showing a card with only "You Support" on the candidate page, along with the organization cards (since your support or opposition will be shown in the Candidate header that Jeff designed). That needs to be fixed.

We will need to show a position card from the voter once a voter adds a comment (we will be adding voter comments in the next major version). I will add a filter within WebApp to only show this "voter comment card" if there is a comment associated with the position, which means that this card will not be shown until later versions.

**Comment by DaleMcGrew** [comment]
This is now fixed and live. @lisamcho
