### ISSUE TITLE
Ballot not loaded unless you click "Save Address"

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#224]
1. Make sure you are connected to API server (as opposed to local WeVoteServer)
2. Clear "voter_device_id" from cookies
3. Visit WebApp, and you are redirected to intro page: http://localhost:3000/intro
4. You should see an address in the top navigation bar. Do NOT click "Save Address"
5. Click on the "Ballot" icon, and you are taken to an empty ballot page.

Proposed solution: If we get to the ballot page and the ballot is empty, reach out to API server. (voterBallotItemsRetrieve? voterAddressSave?)

**Comment by lisamcho** [comment]
Can't reproduce. I get a blank address in top navigation bar in step #4.

**Comment by DaleMcGrew** [comment]
@lisamcho Are you on Wifi connected to a building, or on a mobile device via cell phone service?

**Comment by lisamcho** [comment]
Wifi on a building.

**Comment by DaleMcGrew** [comment]
Do you get a geo-located address when you use https://wevote.me as opposed to your localhost? We might also need to update our GeoIP address database -- it sounds like your wifi device might have been assigned an IP address we don't recognize.

**Comment by lisamcho** [comment]
I don't get a geo-located address for either wevote.me or localhost. I used to always get "none, none, none". Now I always get blank.

**Comment by lisamcho** [comment]
I think that this bug is caused by the voterAddressRetrieve endpoint returning a bogus google_civic_id....see response below.
{address_found: true, normalized_state: "", normalized_line1: "", guess_if_no_address_saved: true, text_for_map_search: "San Francisco, CA 94110"…}
address_found
:
true
address_type
:
"B"
google_civic_election_id
:
"San Francisco, CA 94110"
guess_if_no_address_saved
:
true
latitude
:
""
longitude
:
""
normalized_city
:
""
normalized_line1
:
""
normalized_line2
:
""
normalized_state
:
""
normalized_zip
:
""
status
:
"VOTER_ADDRESS_NOT_FOUND, GUESS_IF_NO_ADDRESS_SAVED, VOTER_ADDRESS_RETRIEVE-VOTER_LOCATION_FOUND_FROM_IP *** San Francisco, CA 94110 ***, , GOOGLE_CIVIC_API_ERROR: Failed to parse address, VOTER_ADDRESS_RETRIEVE-ADDRESS_FOUND"
success
:
true
text_for_map_search
:
"San Francisco, CA 94110"
voter_device_id
:
"53XYSBMlYpCIu8NONoPxWXBiM9gg1AsPQ4bkOqy7ER0BqI8SVVSW5ULJK8y3dIdq4RDYXBy1YRRzI4SvuSlHZNOx"
__proto__
:
Object

**Comment by DaleMcGrew** [comment]
Thank you @lisamcho, I will take a look ASAP.

**Comment by DaleMcGrew** [comment]
I found the code that was returning "text_for_map_search" where it should have been returning "google_civic_election_id", and I believe that fixed this. It seems to be fixed on my machine.

**Comment by lisamcho** [comment]
I can still reproduce this, but I get the "Enter a different address" box instead of the indefinite loading screen. I think the problem is different now. 
voterRetrieve creates a voterdeviceid fine.
voterAddressRetrieve is called and returns a google_civic_id of 0.
voterBallotItemsRetrieve is called with google_civic_id of 0, but it returns a ballot with google_civic_id of 1000000.

The BallotStore looks for a ballot with id of 0, and doesn't find one, so it returns undefined. I think the correct google_civic_id for the address of San Francisco, CA is not 0 (since that's the test id right?). I think the problem is with either voterAddressRetrieve returning the wrong google_civic_id (of 0, when it should be 1000000).
@DaleMcGrew

**Comment by DaleMcGrew** [comment]
I have updated https://wevote.me with a fix.

**Comment by lisamcho** [comment]
Hey I looked at this again. @DaleMcGrew The exact same thing is happening on Api.wevoteusa (returning google civic id of 0 when you retrieve the user's address, then returning a ballot with a different google civic id.)

**Comment by DaleMcGrew** [comment]
I think I found the problem a little bit ago. I will test in the next couple of hours.

**Comment by DaleMcGrew** [comment]
Hi @lisamcho I just updated the API server and I think it is doing what it should be doing now. I think the solution is to either A) wait to call voterBallotItemsRetrieve until after we have gotten a response from voterAddressRetrieve, or B) Call voterBallotItemsRetrieve again when visiting the /ballot page if we don't have any ballot entries. Can you try that?

**Comment by lisamcho** [comment]
@dale I just retested it, and I'm able to reproduce the issue in the api.wevoteusa.org (completely independent of the javascript app and timing issues). Can you retest it following the steps I've outlined above? I think that the problem is that voterAddressRetrieve returns a civic_id of 0 (when the actual civic id is something else). There's a hack-y way to fix it on the front end (just don't store ballots by their civic_id), but I don't have time to work on this before the bbq, and it would be more correct for the API to return the correct value anyway.

**Comment by DaleMcGrew** [comment]
When I test I always see a google civic election id come back from voterAddressRetrieve. You aren't?

**Comment by DaleMcGrew** [comment]
I see voterBallotItemsRetrieve come back before voterAddressRetrieve completes. If voterBallotItemsRetrieve was delayed until after voterAddressRetrieve, it looks like to me that this problem would be solved. I think also calling voterBallotItemsRetrieve again when visiting the /ballot page (if we don't have any ballot entries) would also add get the data we need.
Note: I am seeing a new problem where sometimes only the offices are retrieved and not the candidates underneath each office. I'm looking into this.

**Comment by lisamcho** [comment]
I see 0 come back as civicid from voteraddressretrieve. That is wrong.

**Comment by DaleMcGrew** [comment]
Hi @lisamcho, I hope you had a good weekend. Maybe we can watch the console together tomorrow night? I am seeing a positive value for google_civic_id in the console, so I'm not seeing voterAddressRetrieve returning 0 any more. I am seeing voterBallotItemsRetrieve getting called before voterAddressRetrieve. Is it difficult to call voterBallotItemsRetrieve on the ballot route if there aren't any ballot items in the BallotStore?

**Comment by lisamcho** [comment]
@DaleMcGrew I can't make it tomorrow, but did you change the API Server? I can no longer reproduce the bug. When I fetch voterAddressRetrieve for a new voter_device_id, I am no longer getting google_civic_id of 0. The ballot is loading fine.

**Comment by DaleMcGrew** [comment]
Hi Lisa, I made a few fixes over the last week to the API server. I still see this bug with the ballot not showing up if I don't save my address, even though I get a google_civic_id back from voterAddressRetrieve..

**Comment by lisamcho** [comment]
@DaleMcGrew ok,  that is weird that is still shows up for you but not me. I'm guessing there is more than one root cause of this bug (wrong civic ids would certainly do it), but calling the api in the wrong order could do it too. 

Re... " Is it difficult to call voterBallotItemsRetrieve on the ballot route if there aren't any ballot items in the BallotStore?" That wouldn't be difficult but I don't think that's a good way to solve the problem. ballotItemsRetrieve is already being called as part of the initialization, shouldn't be a need to call it again. 

Regarding seeing voterBallotItemsRetrieve getting called before voterAddressRetrieve, that ordering is problematic? Hard for me to debug it w/out being able to reproduce the bug. You could try to change the BallotActions.retrieve() call in BallotStore to be called when the store registers an action of voterAddressRetrieve, not voterRetrieve.

**Comment by DaleMcGrew** [comment]
Thank you @lisamcho, I don't believe voterBallotItemsRetrieve will return any items until voterAddressRetrieve is complete, so  I will try this: "You could try to change the BallotActions.retrieve() call in BallotStore to be called when the store registers an action of voterAddressRetrieve, not voterRetrieve."

Thank you for your help debugging this!

**Comment by DaleMcGrew** [comment]
To be verified after Pull Request #296 is merged.

**Comment by lisamcho** [comment]
Cool, I think we're ready to close, finally! That one was epic eh @DaleMcGrew ?

**Comment by DaleMcGrew** [comment]
Yes, that was a tough bug! Thank you for all of the analysis you did so I could solve the core API problems.
