### ISSUE TITLE
Set up UI Automated Testing tool

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#228]
Implement a UI automated testing tool so we can catch breaking changes to the UI. @lisamcho pointed out the need for this. @pertrai1 has some experience with a system and will set this up.

**Comment by pertrai1** [comment]
@DaleMcGrew I looked more into this with being able to use AWS/Docker/Selenium, and there are price factors that would need to be considered if the need is great enough to have this in place. Obviously the testing of source code and functional testing is important to any good application, and also being aware of the pricing will determine if it can be done now. Also will need to keep in mind the time it will take to get others understanding how to do automated UI testing of React components.

**Comment by DaleMcGrew** [comment]
Hi @pertrai1, thank you for doing the research. How can I learn about the pricing considerations?

**Comment by pertrai1** [comment]
@DaleMcGrew @josephevans should be able to help with this in regards to the pricing considerations if UI automation was to be done on demand. https://aws.amazon.com/ecs/

**Comment by DaleMcGrew** [comment]
Note from Joe (May 11, 2016):
I got Selenium installed on our admin VM. You have an account on it and can access via ssh:
ec2-52-34-223-243.us-west-2.compute.amazonaws.com

**Comment by luojxxx** [comment]
I put together a little guide for using cross browser testing cloud services with Selenium's automated testing: https://docs.google.com/document/d/1gDi1eXimhN-7syTt-OK9V6elBWC8F9s9riz_0qH6nek/edit?usp=sharing

It's fairly straightforward it seems. You can use the Selenium Firefox extension to record the website test actions, convert them into Selenium WebDriver format, modify that code to use the Saucelabs/someOtherService cloud, and then watch it on the Saucelabs/someOtherService.

**Comment by alexthornton** [comment]
After discussing a bit with @DaleMcGrew, I'll try to push this one forward a bit. In a hierarchy of testing, it's usually a good idea to start as close to the code as possible with unit tests, then back out to more integration tests that test the full stack with a tool like Selenium (which is fantastic by the way). Unit tests run faster and are less brittle because they test fewer things at a time. Selenium tests, on the other hand, would test both the React and Django apps, meaning that they tend to be slower and more brittle. Unless folks disagree, I'll start with React tests first.

**Comment by DaleMcGrew** [comment]
Hello @alexthornton I wanted to introduce you to @niyatikothari. She is helping We Vote with Quality Assurance as well, so I added her to this case so the two of you can stay synchronized. Thank you!

**Comment by DaleMcGrew** [comment]
This is underway with @niyatikothari and @pertrai1. Thank you!
