### ISSUE TITLE
Update Popovers in BallotItemSupportOpposeCountDisplay

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2324]
Please update to the new popover approach the popovers in this file:
WebApp/src/js/components/Widgets/BallotItemSupportOpposeCountDisplay.jsx

![Screen Shot 2019-06-17 at 3 09 27 PM](https://user-images.githubusercontent.com/7756031/59640302-7cc16a00-9112-11e9-871c-1cbc55a54a9c.png)

![Screen Shot 2019-06-17 at 3 14 20 PM](https://user-images.githubusercontent.com/7756031/59640336-99f63880-9112-11e9-951e-a4aabb2ed363.png)

**Comment by jarodpeachey** [comment]
Just submitted this, but I have one suggestion. I don't know how often users will be viewing the popover and scrolling, but if you do, the popover re-positions so it doesn't scroll out of the view port (normal behavior). However, when you scroll, the popover re-positions and disappears because the mouse is no longer over it. If you wanted to fix this, we could set the hide delay to 400 or 500 milliseconds, so the user has more time to hover back over it.

**Comment by DaleMcGrew** [comment]
Hi @jarodpeachey, yes, please feel to play with the hide delay so it feels good to you. These new popovers look amazing!
