### ISSUE TITLE
Gray area formed on the bottom of the page for the Samsung Galaxy S4 (10.5 inches)

### ISSUE THREAD

**Issue by ffrancetic** [wevote/WebApp#2357]
### Please describe the issue (What happens? What do you expect?)
Gray area formed on the bottom of the page for the Samsung Galaxy S4 (10.5 inches). It is only on the very start of the app. https://localhost:3000/wevoteintro/network

### Steps to reproduce the problem (1, 2, 3...), including links
<img width="404" alt="Screenshot 2019-06-20 at 14 04 39" src="https://user-images.githubusercontent.com/36188818/59881560-c3a69e00-9364-11e9-887f-339402c98725.png">

**Comment by SailingSteve** [comment]
**Suggest "Priority: 3" for this issue.**

The largest device I can simulate with Android Studio, is a Galaxy Tab A, a 10.1" device.  We need a list of devices that we support, and every device on the list will need to be tested fixed by a developer, then tested again in our test suite.  My testing matrix for margins now has 352 permutations to check.  That is without 4" iPhones and 10.1 in Galaxy Tabs.  Ideally we won't be supporting devices older than a few years.

![Screenshot_1561077379](https://user-images.githubusercontent.com/6923653/59889596-f27f3d00-9381-11e9-918d-91fa74acaa6e.png)

**Comment by SailingSteve** [comment]
Info:  Does not reproduce on the 12.9" iPad Pro

**Comment by SailingSteve** [comment]
Samsung Galaxy Tab A -- in simulator
window.screen.width = 902
window.screen.height = 1443
