### ISSUE TITLE
Rename bundle.js on each new version so browsers are forced to refresh

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#244]
Whenever we create a new version of We Vote, I would like the browsers of voters to be forced to grab the latest version. I believe that currently bundle.js gets cached, and will only refresh when forced. Can we change the build process to change the name whenever there is a new version? @nf071590 @josephevans @pertrai1

**Comment by pertrai1** [comment]
@DaleMcGrew Yes we can add a cache buster timestamp to the name of the file so that it is seen as a new file and will be downloaded. The best way to do this is to add the timestamp to the end of the file name like so:

`bundle.xxxx.js` so that it is seen as a new file

Browsers are not all supportive of the use of `bundle.js?xxxx` and will not recognize the difference, so the safest way to do this is the first approach.

**Comment by DaleMcGrew** [comment]
Bumping to @pertrai1 so we can tackle today.

**Comment by nf071590** [comment]
We should use version number instead of timestamp.

**Comment by pertrai1** [comment]
@nf071590 Can you work with me on this. I have been trying some gulp plugins for cache busting but have not been able to get it working with `bundle.js`

**Comment by pertrai1** [comment]
@nf071590 so far I have tried gulp-rev and gulp-cache-bust but to no avail.

**Comment by DaleMcGrew** [comment]
@josephevans is this renaming of bundle.js something you can do in your release process, or does @nf071590 need to do this update in the npm build process?

**Comment by josephevans** [comment]
Sure! I just finished this and it's running in production on wevote.me. When a new version is installed, it changes index.html to point to "bundle-TIMESTAMP.js" and renames the javascript file.

**Comment by DaleMcGrew** [comment]
Thank you!
