### ISSUE TITLE
Instant Search: submitting search with "Enter" should work

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#334]
1. Type a search term in the Instant search box
2a. One result appears
3a. Hit return on keyboard. Navigate to that one result

2b. Multiple results appear.
3b. Hit return on keyboard. Navigate to the first result

This works:
2c. Multiple results appear.
3c. Tab down to one result
4c. Hit return on keyboard. Navigate to the selected result

**Comment by pertrai1** [comment]
@DaleMcGrew I think there will need to be more conversation and details about this. I have played around with some of your replications and was not able to follow them completely. The expected behavior I would imagine is that a person would tab to the choice that they want. If the enter desire is that there is a typeahead that will populate the input with the closest match so that hitting the enter key will take you to that result, that can be accomplished.

**Comment by DaleMcGrew** [comment]
Hi Rob, you are right -- if someone hits return (or clicks the search button), it should populate the box with the first search result and navigate to that entry.

**Comment by abbynormative** [comment]
I have a solution that partially does what you want for this. I am stuck on handling what happens when there are truly "no results." See code below with comments.
Added to the render function in SearchAllBox.js
`onKeyPress={this.handleKeyPress}` 
Added above the render fuction
`  handleKeyPress(e) {
    if (e.key === 'Enter') {
      console.log('pressed enter');
      var results = document.getElementsByClassName('search-container__results');
      console.log(results[0]);
      //test if search results are empty
      if(results[0]=='null'){
        console.log("no results");
        //but there will always be results because of autocomplete?
        //stop submit somehow - where is the function that submits the search when you press enter?
        //need to test results from SearchAll somehow
        
      }
      else{
        results[0].click();
        //can see brief loading screen that says "Candidate not found" before loading the page for first result
      }
    }
  }`

**Comment by DaleMcGrew** [comment]
This if working now. Great work @abbynormative!
