### ISSUE TITLE
Create "Office" page/route

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#400]
Create a page where you can see all of the candidates running for a particular office. 

Background: We are moving towards the ballot page being only an index page with a list of all offices and measures, so we need a page to display just one office and all of the candidates running for that office.

**Comment by nickbarry** [comment]
@zachmonteith and @DaleMcGrew , I'd like to help out with this, and don't want to step on anyone's toes. What's the current status of this? I see that Root.js already has an /office route on line 87 (based on the code I pulled down last week):

`<Route path="/office/:we_vote_id" component={Office} />`

I'm happy to look through the code and figure out what's done and what isn't, but if either of you know the answer off the top of your head, let me know. Otherwise, please don't spend any time searching the codebase to answer my question - just let me know you'd like me to do that :)

**Comment by nickbarry** [comment]
@DaleMcGrew says this one is already well in hand - I'll work on something else.

**Comment by DaleMcGrew** [comment]
Fixed and live.
