### ISSUE TITLE
#3 & #4 Ballot Page: New top-of-ballot design needed, rework into tab format

### ISSUE THREAD

**Issue by tiffanysun** [wevote/WebApp#440]
We need a design for the top of the ballot. 

3) On [Landing Page](https://wevote.me/ballot), the spacing between dropdown and text surrounding should have more spacing. 
<img width="646" alt="screen shot 2016-09-06 at 12 44 09 pm" src="https://cloud.githubusercontent.com/assets/12804592/18296544/3f20f4c2-745f-11e6-90da-2d5199071bb4.png">

4) Instead of dropdown, rework these as tabs (ie: Remaining Choices, Support, Bookmark)
<img width="355" alt="screen shot 2016-09-06 at 12 44 16 pm" src="https://cloud.githubusercontent.com/assets/12804592/18296653/f7d3a4ec-745f-11e6-95e5-245e5d34197a.png">

**Comment by ixley** [comment]
@DaleMcGrew @tiffanysun I'm attaching an **in progress** mockup where I am exploring some wider reaching navigation cleanup, but since it also addresses this issue's notion of switching Ballot filterning navigation from dropdown to tabs, I thought I would share it for feedback. 

Of course, the singular change of switching from dropdown to tabs is relatively simple such that it doesn't necessarily require a larger design shift, but since we are prioritizing visual cleanup in general right now, I thought it might be helpful to discuss in the context of other possible changes.

![image](https://cloud.githubusercontent.com/assets/160662/18323366/23112896-74ec-11e6-9d04-cc026cf2b3dc.png)

**Comment by DaleMcGrew** [comment]
@ixley I love this direction!!!

**Comment by ixley** [comment]
@DaleMcGrew awesome! It's still closer to concept (exploring ideas) than implementation-ready, but let's find time to discuss.

**Comment by DaleMcGrew** [comment]
Completed!
