### ISSUE TITLE
Mobile: Measure card has left-spacing that can be removed

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#446]
There is space on the Measure card in mobile mode that is left-over from the candidate photo. This space can be removed. The spacing does not exist in desktop mode.
![screen shot 2016-09-07 at 8 12 53 am](https://cloud.githubusercontent.com/assets/7756031/18317416/ed231af0-74d2-11e6-8a32-b021ac141a8d.png)

**Comment by ixley** [comment]
This is due to the 'media-object' pattern (though it's likely being positioned inconsistently if it forces empty spacing on small screens and not larger ones).

The pattern assumes there will (or should) be an image/avatar to the left of the text. Forcing the spacing (leaving blank space when there is no image) is probably appropriate when there should be an image (but in that case there should at least be a generic placeholder image). If Measure items will _never_ have images, we can adopt a different layout (the simplest would just be to only conditionally show the wrapper/container div for the avatar that sets the spacing). 

In addition to accommodating a fix that doesn't create a gap when there is no image at all, I would suggest exploring whether it would be appropriate to have customized images for Measures. If they will (almost) always be one or two letters or numbers, could we display that as the 'avatar'?

**Comment by DaleMcGrew** [comment]
Measures will not have images like Candidates do, but that is a cool idea to use the 1-3 character measure label as a auto-generated avatar.

**Comment by ixley** [comment]
Ok, the most direct and flexible fix then would be to make the avatar container `measure-card__media-object-anchor` conditional and only render if there is an image (or placeholder).

We can explore adding an auto-generated image later.
