### ISSUE TITLE
Support/Oppose buttons stack vertically on small phones

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#471]
### Please describe the issue (What happens? What do you expect?)
On all phones, the "Support" and "Oppose" buttons stack one on top of the other. I think we can remove the text ("Support" and "Oppose") for those two buttons when the view is too small. The Public/private toggle also overlaps the "Share" button on some phones.
### Steps to reproduce the problem (1, 2, 3...), including links
1. Go to local ballot "Oakland, CA 94602"
2. Look at any proposition where you haven't taken a position yet, and notice the stacked  "Support" and "Oppose" buttons

![screen shot 2016-09-16 at 7 36 30 am](https://cloud.githubusercontent.com/assets/7756031/18589615/5cf0b2e8-7be0-11e6-80db-fbae9ce46000.png)

Example of public/private toggle covering "Share" button:
![img_2421](https://cloud.githubusercontent.com/assets/7756031/18590543/208ae6bc-7be4-11e6-8a4c-8c811d697a6c.PNG)

**Comment by DaleMcGrew** [comment]
Verified!

**Comment by ixley** [comment]
I appreciate saving space by removing the text labels on small screens, but I wonder if it makes more sense to hide the 'Share' label (instead of 'Support/Oppose') because 1) sharing is more a secondary action, and 2) the thumbs up/down icons look very similar without labels and/or coloring. Thoughts @DaleMcGrew @zachmonteith ?

![image](https://cloud.githubusercontent.com/assets/160662/18771631/50712f92-80f5-11e6-890e-7bad90336e47.png)

**Comment by DaleMcGrew** [comment]
Hi @ixley I would be worried that removing just the word "Share" won't reclaim enough horizontal width on the smaller phones. I also think the "thumbs up" and "thumbs down" icons are easier to figure out than the share icon (without the word).

**Comment by zachmonteith** [comment]
I thought about removing the word Share but I agree with @DaleMcGrew, the symbol is slightly more ambiguous and also we want to be encouraging users to share in order to scale up quickly.

I like the idea of color coding the icons though!  Same color scheme we are currently using for the positions you have already taken would look good and maintain consistency.  I also don't think this would confuse users as the other option disappears once you pick one, so the ability to make the choice/knowledge that you have made your choice is still clear.

**Comment by ixley** [comment]
Though I agree color can help with distinction, I don't think adding color in this context is appropriate. If you guys both prefer Share have the emphasis here, that's fine.
