### ISSUE TITLE
Firefox: Weird icons on voter guide page

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#509]
### Please describe the issue (What happens? What do you expect?)
1. On Mac Firefox, go to: https://wevote.us/theleaguesf
2. You will see many icons displayed left-to-right, when it should only show one

<img width="639" alt="screen shot 2016-09-28 at 7 55 17 pm" src="https://cloud.githubusercontent.com/assets/7756031/18939509/ab9f5154-85b5-11e6-9500-198f435c8d33.png">

**Comment by ixley** [comment]
Fun! So it appears that it's something to do with the image handling. What's rendering is the image alt text 'candidate-photo' using the sizing and icon font intended for the placeholder icons. So while Webkit seems to trigger the image handler to swap out the image tag for the placeholder icons (`<i class="icon-icon-person-placeholder-6-1... >`, Firefox, in these cases is leaving the `image` tag that then renders the alt text with the icon font, (though it doesn't seem to be failing all the time since the placeholder icons do show up in some cases).

Since I'm less familiar with how the `<ImageHandler>` component works and how it does or doesn't identify the error state, I'll assume someone else can field this better than I.

**Comment by DaleMcGrew** [comment]
Verified! Thank you @zachmonteith.
