### ISSUE TITLE
Can't make positions public or share 'Your Page' without Twitter account

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#585]
### The issue
This functionality might just not exist yet, but because @DaleMcGrew mentioned that it _should_ work and the UX is confusing, I'm filing as a bug. 

If your account is only linked to an email (and not a Twitter account), it appears that you cannot make positions public. This is confusing however, because you can still set the visibility toggle to 'public,' it just resets when you navigate away. If a user cannot make positions public, they should not be able to set the toggle to 'public' and should be given an appropriate message to let them know.

**Comment by DaleMcGrew** [comment]
Thank you Jeff! I totally agree.  When someone (who is not signed in) clicks on that "make public" toggle,  I am imagining that they would get a little pop-up that said something like "please sign in to share your opinions publicly". (Note: I am healing the data so that everyone who signed in has a page they can share publicly regardless of how they signed in.) What do you think is the best interface for that?

**Comment by ixley** [comment]
The combination of bugs and unpolished UX often makes it difficult for me to tell what the intended behavior is... @DaleMcGrew Do you have any of these flows mapped out? Perhaps it would be useful for us to do that since there is a good amount of behind-the-scenes complexity with sign-in related flows? They could be diagrams or just text scenarios...

**Comment by DaleMcGrew** [comment]
Closing because this is on the upcoming feature roadmap.
