### ISSUE TITLE
Medium blog on our domain

### ISSUE THREAD

**Issue by ColettePhair** [wevote/WebApp#612]
Our blog currently exists only on Medium.com.  To benefit from SEO, drive traffic to our site, and keep everything in one place, we should link our Medium blog to the WeVote.us domain.

The "M" Medium social link at the top of https://wevote.us/more/about can also be changed to link to our blog on our own domain.

Here is an article on linking Medium to one's own site:  https://help.medium.com/hc/en-us/articles/217991468-Duplicate-Content-and-SEO

**Comment by ixley** [comment]
@ColettePhair There are two separate things here. I'm assuming you're primarily referring to setting up a custom domain for Medium posts, such as blog.wevote.us. This requires first setting up a Medium Publication since custom domains cannot point to user profiles (@wevote). https://help.medium.com/hc/en-us/articles/213474588-How-do-I-set-up-a-custom-domain

The post you linked to is about duplicate content and SEO considerations for canonical URLs, which is a different issue that probably isn't relevant to us right now. It addresses the case for when you are publishing the same content in two places, which it doesn't seem we are doing.

**Comment by ColettePhair** [comment]
@ixley What I'd like is for our Medium blog posts to be posted in two places - on Medium and on our site, in a way that doesn't disturb SEO.  (Right now we're losing out on SEO with our blog only existing on Medium.)  My understanding is that this is possible, though I'm not aware of the details of how to implement it - one reason I'm hoping one of the engineers can help out with this. ( :

**Comment by ixley** [comment]
@ColettePhair I may be misinterpreting what your goal is, but my impression is that you want blog posts that you continue to write/post using Medium's platform to be accessible via blog.wevote.us (or somesuch). In this scenario, you get the branding benefits of having content associated with our domain (plus the SEO association/benefit that goes along with that) and get to continue to use Medium's writing and cross-promotional platform.

The original support post you linked to is about publishing duplicate content to two different places and then making sure that search engines are aware that they are mirrored content. This is less likely what you want to do since we are not currently double publishing, and there is no real benefit to start doing so at this stage (IMO). If you're just trying to get search engine love, setting up a custom domain and associating it with a Medium Publication should be all you need to do and it will be pretty straightforward.

You'll need someone who can create the subdomain you want in the first place, perhaps @DaleMcGrew – and then you should be able to do most of the rest yourself via Medium's platform.

**Comment by ColettePhair** [comment]
Okay, thanks, I think I understand now.  If @DaleMcGrew wants to create it I can do what I need to do on my end.

**Comment by DaleMcGrew** [comment]
We will manage this task separate from github. Closing for now.
