### ISSUE TITLE
Facebook Login uses popup, which gets blocked by most browsers

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#662]
### Please describe the issue (What happens? What do you expect?)
The current Facebook sign in we are using uses a pop-up. When user testing, I notice that many browsers block the popup needed for Facebook sign in. We need a solution that doesn't use a popup that gets blocked by browser defaults.
Note: We avoid a problem with popup blockers with Twitter because it does a browser redirect.

### Steps to reproduce the problem (1, 2, 3...), including links
1. Turn on your browser's popup blocker.
2. Go to https://wevote.us/more/sign_in and click the Facebook Sign in button.
3. You should see an indicator that the popup has been blocked.

**Comment by jainanisha90** [comment]
Popup action for that facebook login(FB.login) is not caused by a click event in wevote, we are calling FB.login from the fallback of FB.getLoginStatus from where popup blocker is triggering.

FB.getLoginStatus does an ajax call and when you call FB.login on it's response, the popup that would open  as a result of this call is blocked. There are two solution stated below:
1.  Initiate your FB.login code on click of login button
OR
2.  Specify status: true in the options object of FB.init and you need to be confident that login status has already loaded.

I am fixing this issue by specifying status as True as we called FB.login through FB.getLoginStatus.

References:
http://stackoverflow.com/questions/16559115/fb-login-popup-block
http://stackoverflow.com/questions/7125320/facebook-login-without-pop-up

**Comment by DaleMcGrew** [comment]
Fixed!
