### ISSUE TITLE
Show "Loading" text immediately from WebApp/src/index.html file

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#746]
### Please describe the issue (What happens? What do you expect?)
When accessing We Vote on a smart phone when there isn't great reception, I have seen a white screen for 6 seconds before the blue "We Vote Loading" screen appears. I would like a blue screen with the words "We Vote Loading" to appear within 1 second of visiting the site (i.e. before the Javascript bundle loads).

**Comment by Anoninnyc** [comment]
@DaleMcGrew Sooo.....
We add a blank screen in a div tag to index.html.
Then ComponentDidMount for the app, we remove it with jQuery?

**Comment by Anoninnyc** [comment]
@DaleMcGrew  Took a closer look at your request and the HTML file. 

So, the spinner that's parsed in html seems to be parsed well before the bundle script is executed already.
The only thing of substance that's parsed before the spinner are the CSS files... so, maybe we could defer them with something like [this](https://www.giftofspeed.com/defer-loading-css/)?

I want to make sure I'm grasping the problem correctly. 

(I'm assuming the sever is feeding back just the html doc on initial load... or maybe I'm missing something?)

**Comment by Anoninnyc** [comment]
Or this.... http://stackoverflow.com/a/22255132

**Comment by DaleMcGrew** [comment]
@nf071590 or @pertrai1 do either of you have any thoughts about how to show a loading message instead of a white screen when someone first arrives at https://WeVote.US?

**Comment by Anoninnyc** [comment]
(GPRS make sure no cache)

**Comment by Anoninnyc** [comment]
@DaleMcGrew  Isolating the prblem: seems like culprit for slow download are indeed the link tags. `

<title> We Vote </title>
  <script>console.log("Logging to test speed");</script>
  <meta charset="utf-8">
`

**Comment by Anoninnyc** [comment]
@DaleMcGrew 
Insights so far: If I remove all of the stylesheet tags, Loading appears nearly asap, even on the crappiest network connection. 

However, if I includeeven one locally hosted stylesheet (even when minified) and put inline (i.e. in ), the GSPS-level connection takes so long to parse thru the inline css, it's still unbearable.

**Comment by Anoninnyc** [comment]
@DaleMcGrew 
Hi Dale, 
See my Do Not Merge PR , specifically, what I did to the link tags in index.html. Basically I'm deferring their download. The trade-off is that, because the spinner relies on bootstrap, it doesn't show.  However, the word "Loading" shows immediately. 

I might be able to dissect bootstrap and pull out the spinner-related classes, then put them inline in "style" tags above the spinner div.

It's also worth noting that the script tag I put after the title that console logs something.... it shows up nearly immediately after refreshing.

Ideally, we should minify our css/main.css, file. It seems to already be concatenated.

**Comment by Anoninnyc** [comment]
Also, please let me know how it looks on your end...

**Comment by DaleMcGrew** [comment]
Fixed.
