### ISSUE TITLE
Analyze size of current react plugins in production

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#776]
Ideally we can reduce the size of our compiled react bundle. I suspect that we are using a few react plugins that are quite large that we could phase out. To resolve this issue:

Step 1:
- [ ] Find out the size of every react plugin we are using (as described in WebApp/package.json), so we can discuss whether or not we need to use each plugin

Step 2:
- [ ] Make sure we are using all of the plugins listed. Can we remove any from Production without breaking anything?

Step 3:
- [ ] Are any plugins excessively large? Can we refactor to reduce reliance on those plugins?

**Comment by clapinton** [comment]
I got the size of all packages using the `cost-of-modules` npm package, tabled the results and added prod and dev flags, depending on the dependency (also added hyperlinks to the npm page itself on the first column). Note that a bunch of children are shared between packages (if you add up the Children column, you'll get 2800+ children, vs the real total of 1051). Same goes for the size. There's another package that gives out which children are under each package, but we have to run a script for each dependency. I suggest we figure out which ones we have to keep, check the children under them vs the children under other packages to see what we could really get rid of.

https://docs.google.com/spreadsheets/d/1mINBClQJ8CBd8e4rceE8ZvXPJXZE4d6dxa9Tp5OcCo0/edit?usp=sharing

**Comment by DaleMcGrew** [comment]
Thank you Eric for spearheading this. Please let me know if you need help with any of these steps.

**Comment by Anoninnyc** [comment]
@DaleMcGrew @clapinton Are we doing this [this](http://stackoverflow.com/a/34241128) in our code, like here:[]( https://github.com/wevote/WebApp/blob/develop/src/js/components/DonationForm.jsx#L2)

**Comment by DaleMcGrew** [comment]
Hi @Anoninnyc and @clapinton it looks like there might be some opportunities to reduce the size of our production bundle based on how we included portions of some of these bigger packages.

**Comment by Anoninnyc** [comment]
yup... @clapinton- we're not tying to optimize the dev deps, correct- just production deps?
Wanted to clarify...

**Comment by clapinton** [comment]
@Anoninnyc it is just the prod ones. I tabled the dev ones since it wasn't too much work and thought it might come in handy at some point. Still, I'm focusing on the prod ones.

I went through all `dependencies` and added some comments to that spreadsheet above. Overall, here's what we could tackle:
* `react-headroom` (14.8M and 7 children) is the biggest package. It's only required on Application.jsx to hide the header when the user scrolls. I think we can switch to a lighter package, such as the original `headroom.js` (not specific to React, but easy to readapt), or some other similar;
* `moment-timezone` (5M and 1 child) is not being required/imported or used anywhere. Another package called `moment` is used to format datetime. I removed the `moment-timezone` folder from my node-modules, deleted bundle.js and rebuilt everything. Everything seems to work properly, so it all points to being ok to remove;
* `moment` (2.2M and 0 children) is used in a total of 4 lines of codes to format datetime variables. We might be able to find a smaller package for this, or even build our own formatting script;

Also, there's a small package called `history` (230KB and 9 children) which appears inside bundle.js, but it's not required/imported anywhere. Removing the node-modules folder breaks bundling, so I'm guessing it comes from gulp. Any ideas?

**Comment by DaleMcGrew** [comment]
Great detective work Eric! I will create a separate issue to remove replace react-headroom. We should be able to refactor the API  server to retrieve formatted datetime values so we don't need to do it in React. Thank you!

**Comment by clapinton** [comment]
Makes sense. Do test out the `moment-timezone` on your end as well. I did go through every single page and clicked around to make sure, but it's better to be safe.
Also, I was thinking about the `react-text-truncate` (1.7M and 0 children) package. It's only used inside the ReadMore component, so it might also be fairly easy to switch to a lighter package.

In any case, I can take a look at other options for the `react-headroom` (and maybe the `react-text-truncate` too) and figure out some better, lighter options.

**Comment by DaleMcGrew** [comment]
Thank you @clapinton for your excellent work on this. I am closing this for now given your work on react-headroom, although we might open it again later.
