### ISSUE TITLE
More Opinions - Filter for One Candidate

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#8]
On the main ballot page, the More Opinions page takes you to a list of all Voter Guides that relate to any item on this ballot. This is great. What we need to add is this:
When you are on one candidate's page, clicking on the "More Opinions" should only offer the Voter Guides that have a position relating to that particular candidate. This is the API end point to use, and to example candidates to filter for:
https://api.wevoteusa.org/apis/v1/docs/voterGuidesToFollowRetrieve/
Ben Carson is wv02cand5
Marco Rubio is wv02cand14

As I work with the current MVP (almost ready for 0.9), I think it is currently not possible to find issues that relate to certain candidates, so I am bumping this issue #8 up to be required for us to hit Version 0.9.

**Comment by pertrai1** [comment]
@DaleMcGrew #6, #7, and this one all the look same to me in the wireframes. Possibly add more information as to what should be added.

**Comment by DaleMcGrew** [comment]
This is almost done. There is still some work to be done creating the link to this page, from the candidate page.

**Comment by DaleMcGrew** [comment]
Completed in my pull request #166 today.

**Comment by lisamcho** [comment]
@DaleMcGrew looking good! Not quite done though...
1. When you fetch new opinions for a candidate, then navigate to Opinions I'm following, then navigate to /opinions, it shows the opinions for the candidate still rather than all the opinions to follow. 
2. When you refresh an opinions/wv12345 page, you get the address not found, even if there is an address (Enter your address so we can find voter guides to follow.)

**Comment by DaleMcGrew** [comment]
Thank you @lisamcho, I am going to create new issues for both items you found, and close this issue.
