### ISSUE TITLE
Voter guide "tab" width adjustment in mobile

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#881]
When viewing an organization's voter guide in mobile mode (iPhone 5 or smaller):
https://wevote.us/ACLU
...the tabs wrap to a second vertical line:
![screen shot 2017-06-05 at 8 57 53 am](https://cloud.githubusercontent.com/assets/7756031/26791885/66fcc270-49cd-11e7-8ad8-cbdcc715d10f.png)

Please adjust the html/css so that they don't wrap on very small screens. Code here:
WebApp/src/js/routes/Guide/OrganizationVoterGuideTabs.jsx and the style is "tabbed_voter_guide_details"

**Comment by pertrai1** [comment]
@DaleMcGrew see https://github.com/wevote/WebApp/pull/894 PR for this fix

**Comment by DaleMcGrew** [comment]
Hi @pertrai1, I had to comment out your change (before I could test it on the live server) because I was getting these linting errors:
src/sass/overrides/_overrides.scss
 21:5  ✖  Unexpected type selector           selector-no-type                 
 23:9  ✖  Expected variable for "padding".   sh-waqar/declaration-use-variable

When you have a moment, could you please take a look?

**Comment by pertrai1** [comment]
@DaleMcGrew I am not sure what these errors represent. I would have to ask @ixley to look at this code and explain what these errors are for so I can make the fix. As soon as we here back from @ixley I will make the change to get these errors removed.

**Comment by pertrai1** [comment]
@ixley can you explain what you have done to fix this issue? Commenting out the previous commit, does that fix the issue?

**Comment by ixley** [comment]
@pertrai1 Instead of using the override you added, I went with a simpler option and just changed the uppercase text to title case so it would fit (lowercase takes up less space and full uppercase labels didn't seem justified or necessary here). Here's my rationale along with some context for the errors you ran into.

- This issue was an extremely specific edge case and so even using a style override felt heavy handed.
- In a case where a style override is necessary or appropriate, the override should be scoped to the specific case(s) it is meant to address. This would probably mean assigning a specific css class or handle to target the appropriate case.
- The linter rules you bumped into could certainly be made clearer, but this is what they do:
  - `selector-no-type` is meant to disallow targeting with any raw element type selectors (such as `li`, `a`, etc.) Styling should only use classes for targeting.
  - `sh-waqar/declaration-use-variable` has a list of properties that require variables instead of raw values. This is an attempt to enforce scale values for spacing and sizing, and limit colors to a palette. Had we kept the override, it would have required something like `padding: $space-sm $space-xs;` (rendering: `padding: 8px 4px;`)
- Additionally, there's no rule to force it, but there's also a mixin to use for media queries which is preferable for consistency. (`@mixin breakpoints`)

**Comment by pertrai1** [comment]
@ixley thank you for the clarification in regards to the rules. Just so I understand, are you saying that when I resize the browser, I will see text go from uppercase to title case? I find that linter rule for selector-no-type interesting considering that this was the rule that was being overridden from Bootstrap. They better start using that rule themselves. 

In regards to the rest of the rules you mentioned, do you have a place somewhere such as the wiki where you reference these style rules along with the likes of a palette? 

Thank you again for looking at this and fixing it up accordingly.

**Comment by ixley** [comment]
@pertrai1 I just realized that GH linked a weird partial commit here instead of what I pushed directly to the wevote repo. (No, just commenting out your changes was not the fix.) See this instead: https://github.com/wevote/WebApp/compare/voter-tab-guide-iphone-alignment

**Comment by pertrai1** [comment]
@ixley Ah that makes much more sense now. Now I do see the markdown file for styling.

**Comment by ixley** [comment]
@pertrai1 
- I changed it to be title case only, never uppercase. (I'm sure it was a somewhat intentional choice to use uppercase, but I don't think it's justified unless someone wants to make a stronger case for it.)
- re Bootstrap inconsistency. So yeah, I think their usage of type selectors in that case is not unreasonable. With a project like ours though, I think it opens up too much room for styles to bleed out when others aren't aware of the cascade. Even in this case, I felt like adjusting all `.nav > li > a` elements was overkill and could have unintended reach.
- There's always room for exceptions but my goal with these linters is to keep things more consistent and clean, especially with so many contributors, most of which are not that familiar with CSS styling.
- Eventually, I'd still like to move away from CSS and restrict styles to component specific parameters, but until then...

**Comment by DaleMcGrew** [comment]
Hello @ixley, your fix solved the problem when looking at voter guides for other people/groups. Thank you! The tabs are splitting to a second line when you are looking at your own voter guide on iPhone 5 and 6:
<img width="342" alt="screen shot 2017-06-17 at 2 48 41 pm" src="https://user-images.githubusercontent.com/7756031/27256520-46c8d702-536c-11e7-84a8-8eedf2148e0e.png">

**Comment by ixley** [comment]
@dalemcgrew If this matters to you I would suggest keeping the same short labels or considering a different nav style that looks better when wrapping. (I personally don't think it's that significant in this specific context.)

**Comment by DaleMcGrew** [comment]
I'm thinking on mobile we can hide "You Are" and only show the full "You Are Following" on desktop. Even with that change, I think the tabs may still need some padding or margins shaved off for iPhone 5.

**Comment by pertrai1** [comment]
@DaleMcGrew @ixley I see know reason why this can't work. The biggest hurdle is around "You Are Following", which can be changed to "You're Following" and it fits fine with adjustments to padding and some other changes to the box model. I will leave it up to @ixley to come up with the game plan as he always does well with this and I can lend support if needed.

**Comment by pertrai1** [comment]
@ixley when you are referring to component style, are you referring to CSS in JS or just having it where the file is located in the same location as the component and the top level root for the style is encapsulated by the element that is the component? The 2nd one is easy to get moving whereas the 1st one would take some time for people to get the hang of how to do it. Explain in more detail what it is that you are wanting to do. 

Also, don't be concerned about having to override with far reaching cascades that are needed against frameworks such as Bootstrap. That is why the likes of Angular team are starting to get away from people using Bootstrap because of the limitations and how you have to mutate the prototype. 

Let me know if I can be of help with componentizing your CSS.

**Comment by ixley** [comment]
@pertrai1 Thanks Rob. Ultimately, I'd like to move towards encapsulated JS styling, but as I've mentioned I don't currently feel confident enough to lead the effort myself. My ultimate goal is to build towards a more unified system in support of a more cohesive design/experience AND to make it easier for contributors (especially those less familiar with design or styling) to insert and construct components with predefined parameters (so there's less ability to stray from conventions). I've tried a couple things via convention—adding utility classes in the absence of clearly defined components, for example), or enabling linters—but it still feels like an uphill battle when I have such limited time/ability to contribute. I'm certainly open to any suggestions you have here!

**Comment by DaleMcGrew** [comment]
Thank you @edward-ly for taking this on.

**Comment by DaleMcGrew** [comment]
This is so much better @edward-ly! Thank you for fixing this.
