### ISSUE TITLE
'best guess' address alert persists even with explicitly entered address

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#983]
The 'best guess' address alert seems to persist even when an explicit address has been entered.

![image](https://user-images.githubusercontent.com/160662/28750365-5ab951a4-749d-11e7-8fa0-6dada7fc3a24.png)

**Comment by edward-ly** [comment]
I had this discussion with @DaleMcGrew before. The source of the issue is that the value of the `normalized_line1` property of the address object received by `VoterStore.getAddressObject()` is always an empty string regardless of the input address, supposedly because there are no active elections going on right now. We'll test whether the alert persists or not (whether `normalized_line1` changes or not) when we can find an active election.

**Comment by DaleMcGrew** [comment]
I have done quite a few updates to this Edit Address alert. It still isn't fully finished, but at least this issue is resolved. It is not quite ready to text extensively yet.
