### ISSUE TITLE
Tab overflow on mobile devices to be implemented

### ISSUE THREAD

**Issue by edward-ly** [wevote/WebApp#999]
### Please describe the issue (What happens? What do you expect?)

As a follow-up to #957, we want to implement the BallotFilter tabs on the ballot page so that, on mobile devices, they overflow to the right and the user can scroll between them. Currently, the ballot look like this:

![screenshot 2017-08-03 14 57 06](https://user-images.githubusercontent.com/11434331/28945725-7b4b3172-785c-11e7-9aca-cc9bb53ce996.png)

### Steps to reproduce the problem (1, 2, 3...), including links

1. Go to http://localhost:3000/ballot
2. Open your browser's developer tools (Ctrl + Shift + I on Windows)
3. Enable the toggle device toolbar (Ctrl + Shift + M on Windows)
4. Select "iPhone 5" or a similar display in the menu above the web page

**Comment by DaleMcGrew** [comment]
Hi @edward-ly, this is a great step forward. Thank you. I have two requests:
1) Prevent scrolling when all of the tabs are narrower than the space they are in (so the horizontal scrolling wouldn't happen in desktop mode). 
2) Only scroll to the right so that you can see all of the text that is off-screen to the right. Currently you can scroll to the right so that the tabs are completely gone.

Thanks!

**Comment by DaleMcGrew** [comment]
Excellent work @edward-ly -- this issue is now closed.
